apiVersion: v1
kind: Secret
metadata:
  name: ska-sdp-qa-secret
type: Opaque
data:
  # Fake secrets to get the SDP QA Display to start.
  # If one needs to use the Login button on the Display, they
  # need to make sure correct secrets are added. This is for
  # testing only (Login won't work).
  REACT_APP_MSENTRA_CLIENT_ID: Y2xpZW50X2lk  # client_id
  REACT_APP_MSENTRA_TENANT_ID: dGVuYW50X2lk  # tenant_id
